serverAddr = "frp地址"
serverPort = frp端口
auth.method = "token"
auth.token = "frp认证密钥"
transport.poolCount = 1
transport.tcpMux = true
transport.tcpMuxKeepaliveInterval = 60
transport.protocol = "tcp"
dnsServer = "223.5.5.5"

[[proxies]]
name = "frp名称"
type = "tcp"
localIP = "127.0.0.1"
localPort = 10023
remotePort = 10002