name: Download and Upload File

on:
  workflow_dispatch:

jobs:
  download-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download
      run: |
        wget https://gitee.com/lntls/reex/releases/download/v1.8.9/armeabi-v7a-release-v1.8.9.apk
        wget https://gitee.com/lntls/reex/releases/download/v1.8.9/arm64-v8a-release-v1.8.9.apk
        wget https://gitee.com/lntls/reex/releases/download/v1.8.9/x86_64-release-v1.8.9.apk

    - name: Move
      run: |
        mkdir -p Reex
        mv armeabi-v7a-release-v1.8.9.apk Reex/
        mv arm64-v8a-release-v1.8.9.apk Reex/
        mv x86_64-release-v1.8.9.apk Reex/

    - name: Push 
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add Reex/armeabi-v7a-release-v1.8.9.apk Reex/arm64-v8a-release-v1.8.9.apk Reex/x86_64-release-v1.8.9.apk
        git commit -m "233"
        git push
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
