name: Download and Upload forwordpanel

on:
  workflow_dispatch:

jobs:
  download-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Download TAR File
      run: |
        mkdir -p xdpanel
        curl -L -o xdpanel/forwordpanel-1.0.7.tar http://tutu.ovh/iso/dockerimage/xdpanel/forwordpanel-1.0.7.tar

    - name: Commit and Push File
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add xdpanel/forwordpanel-1.0.7.tar
        git commit -m "Add forwordpanel-1.0.7.tar to xdpanel"
        git push
