name: Fetch Termark Release

on:
  workflow_dispatch:

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: main
          lfs: true

      - run: |
          git lfs install

      - run: |
          mkdir -p Termark
          rm -rf Termark/*

      - run: |
          sudo apt-get update && sudo apt-get install -y curl

          urls=(
            "https://f.typesafe.cn/termark/Termark-1.0.35-arm64.dmg"
            "https://f.typesafe.cn/termark/Termark-1.0.35.dmg"
            "https://f.typesafe.cn/termark/Termark-Setup-1.0.35-x64.exe"
            "https://f.typesafe.cn/termark/Termark-1.0.35-portable-x64.zip"
            "https://f.typesafe.cn/termark/Termark-1.0.35.AppImage"
            "https://f.typesafe.cn/termark/termark_1.0.35_amd64.deb"
          )

          for url in "${urls[@]}"; do
            curl -L -o "Termark/$(basename "$url")" "$url"
          done

      - run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

          git add Termark
          git commit -m "Update Termark 1.0.35" || exit 0

      - run: |
          git lfs track "Termark/*"
          git add .gitattributes
          git push origin main
