name: Build Reala Linux

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - run: git clone https://github.com/hanyu-dev/reala-legacy reala-src

      - working-directory: reala-src
        run: cargo build --release --target ${{ matrix.target }}

      - run: |
          mkdir -p reala
          cp reala-src/target/${{ matrix.target }}/release/reala reala/reala-${{ matrix.target }}

      - run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add reala
          git commit -m "Add linux binaries for ${{ matrix.target }}" || true
          git push
